name: Homework_Allocator


run-name: ${{ github.actor }}Allocator
on:
  push:
    branches:
      - master
      - feature/github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build .
      - run: cmake --build . --target package
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
  - name: build-deb-action
  # You may pin to the exact commit or the version.
  # uses: jiro4989/build-deb-action@d38d2efb9670d446ad836cc638d9fe871524af6b
  uses: jiro4989/build-deb-action@v2
  with:
    # Package name of debian package.
    package: main
    # Directory of release files.
    package_root: ./
    # Package maintainer name.
    maintainer: application/vnd.debian.binary-package
    # Package version.
    version: 1

    compress_type: # optional, default is gzip